modules/admin/controllers/TextBlockController.php
<?php

namespace app\modules\admin\controllers;

use app\models\db\TextBlock;
use app\modules\admin\controllers\traits\UpdateTrait;
use app\modules\admin\models\forms\TextBlockForm;
use app\modules\admin\models\search\TextBlockSearch;
use yii\base\Model;
use yii\db\ActiveRecordInterface;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;

class TextBlockController extends AdminBaseController
{
    public $searchModel = TextBlockSearch::class;
    public $formModel = TextBlockForm::class;
    public $objectClass = TextBlock::class;

    use UpdateTrait;

    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new $this->searchModel();
        $dataProvider = $searchModel->search(\Yii::$app->request->get());
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            //'searchModel' => isset($searchModel) ? $searchModel : null,
        ]);
    }

    /**
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionEdit()
    {
        $item = $this->getRequestedObject(\Yii::$app->request->get('id'));

        /** @var Model $model */
        $model = new $this->formModel();
        $model->setAttributes($item->getAttributes());
        $request = \Yii::$app->request;

        if ($request->isPost && $model->load($request->post()) && $model->edit($item)) {
            \Yii::$app->session->setFlash('success', 'Изменения сохранены');
            return $this->redirect(Url::to('/' . $this->getUniqueId()));
        } else {
            if ($request->isPost) {
                \Yii::$app->session->setFlash('error', 'Ошибка при редактировании записи');
            }

            return $this->render('edit', [
                'model' => $model
            ]);
        }
    }

    /**
     * @param $id
     * @return mixed|ActiveRecordInterface
     * @throws NotFoundHttpException
     */
    protected function getRequestedObject($id)
    {
        if (!$id || !$item = TextBlock::findOne(['identifier' => $id])) {
            $blocks = $blocks = require_once(\Yii::getAlias('@app/config/settings/text_blocks.php'));
            if (!isset($blocks[$id])) {
                throw new NotFoundHttpException();
            }

            $item = new TextBlock([
                'identifier' => $id,
                'name'  => $blocks[$id]['name'],
                'content' => $blocks[$id]['content'],
                'column_type' => $blocks[$id]['column_type']
            ]);
        }

        return $item;
    }
}

modules/admin/views/text-block/_form.php
<?php

use app\models\db\TextBlock;
use app\modules\admin\models\forms\TextBlockForm;
use app\modules\admin\widgets\WisywygWidget;
use yii\helpers\Html;
use app\modules\admin\widgets\Form;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model TextBlockForm */
?>

<div>

    <?php $form = Form::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'name')->textInput(['disabled' => true]) ?>
    <?php
        var_dump($model->column_type);
        switch ($model->column_type) {
            case TextBlock::TYPE_WYSIWYG:
                echo $form->field($model, 'content')->widget(WisywygWidget::class, ['options' => ['rows' => 20]]);
                break;
            case TextBlock::TYPE_INPUT:
                echo $form->field($model, 'content')->textInput();
                break;

            case TextBlock::TYPE_TEXTAREA:
                echo $form->field($model, 'content')->textarea();
                break;

            default:
                throw new \Exception('Неизвестный тип');
        }
    ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Отмена',  Url::to(['text-block/index']), ['class' => 'btn btn-default']) ?>
    </div>

    <?php Form::end(); ?>

</div>

modules/admin/views/text-block/edit.php
<?php

use app\modules\admin\models\forms\TextBlockForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model TextBlockForm */

$this->title = 'Редактирование элемента: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Текстовые блоки', 'url' => Url::to(['text-block/index'])];
$this->params['breadcrumbs'][] = 'Редактировать';
?>
<div class="box">
    <div class="box-body">
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>
    </div>
</div>

modules/admin/views/text-block/index.php
<?php

use app\modules\admin\grid\AdminGridView;
use app\modules\admin\widgets\Actions;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Текстовые блоки';
$this->blocks['content-header'] = $this->title;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-body">
        <table class="table table-bordered table-hover">
            <?=AdminGridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    [
                        'attribute' => 'identifier',
                        'options' => ['width' => '10%']
                    ],
                    [
                        'attribute' => 'name',
                        'options' => ['width' => '10%']
                    ],
                    [
                        'attribute' => 'content',
                        'format' => 'raw',
                        'options' => ['width' => '70%']
                    ],
                    [
                        'label' => 'Действия',
                        'format' => 'raw',
                        'contentOptions' => [
                            'nowrap' => 'nowrap'
                        ],
                        'value' => function($item) {
                            return Actions::widget([
                                'controller' => 'text-block',
                                'item' => $item,
                                'itemKey' => 'identifier',
                                'buttons' => ['edit']
                            ]);
                        }
                    ],
                ]
            ]);
            ?>
        </table>
    </div>
</div>