modules/admin/controllers/AdminController.php
<?php

namespace app\modules\admin\controllers;

use app\modules\admin\AdminModule;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use app\modules\admin\models\LoginForm;

class AdminController extends Controller
{
    /** @var AdminModule */
    public $module;

    /** @var string  */
    public $layout = 'main';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
                'user' => $this->module->admin
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * @return string
     */
    public function actionError()
    {
        $exception = Yii::$app->errorHandler->exception;
        return $this->render('error', [
            'name' => 'Ошибка',
            'message' => $exception->getMessage()
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        $user = $this->module->admin;
        if (!$user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->renderPartial('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        $this->module->admin->logout();

        return $this->goHome();
    }

    /**
     * @param null $defaultUrl
     * @return \yii\console\Response|Response
     */
    public function goBack($defaultUrl = null)
    {
        return Yii::$app->getResponse()->redirect($this->module->admin->getReturnUrl($defaultUrl));
    }
}

modules/admin/controllers/BrandController.php
<?php

namespace app\modules\admin\controllers;

use app\models\db\Brand;
use app\models\db\Catalog;
use app\modules\admin\controllers\traits\CreateTrait;
use app\modules\admin\controllers\traits\DeleteTrait;
use app\modules\admin\controllers\traits\UpdateTrait;
use app\modules\admin\models\forms\BrandForm;
use app\modules\admin\models\search\BaseSearch;
use app\modules\admin\models\search\BrandAdvantageSearch;
use app\modules\admin\models\search\BrandItemSearch;
use app\modules\admin\models\search\BrandQuoteSearch;
use app\modules\admin\models\search\BrandVideoSearch;
use app\modules\admin\models\search\CatalogProductSearch;
use app\modules\admin\models\search\CatalogSearch;
use yii\web\NotFoundHttpException;

class BrandController extends AdminBaseController
{
    public $searchModel = BaseSearch::class;
    public $formModel = BrandForm::class;
    public $objectClass = Brand::class;

    use CreateTrait, UpdateTrait, DeleteTrait;

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionAdvantages($id)
    {
        if (!$brand = Brand::findOne(['id' => $id])) {
            throw new NotFoundHttpException('Не найден бренд');
        }

        $searchModel = new BrandAdvantageSearch([
            'id_brand' => $brand->id
        ]);
        $dataProvider = $searchModel->search(\Yii::$app->request->get());

        return $this->render('advantages', [
            'brand' => $brand,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionVideo($id)
    {
        if (!$brand = Brand::findOne(['id' => $id])) {
            throw new NotFoundHttpException('Не найден бренд');
        }

        $searchModel = new BrandVideoSearch([
            'id_brand' => $brand->id
        ]);
        $dataProvider = $searchModel->search(\Yii::$app->request->get());

        return $this->render('video', [
            'brand' => $brand,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionQuote($id)
    {
        if (!$brand = Brand::findOne(['id' => $id])) {
            throw new NotFoundHttpException('Не найден бренд');
        }

        $searchModel = new BrandQuoteSearch([
            'id_brand' => $brand->id
        ]);
        $dataProvider = $searchModel->search(\Yii::$app->request->get());

        return $this->render('quote', [
            'brand' => $brand,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionItems($id)
    {
        if (!$brand = Brand::findOne(['id' => $id])) {
            throw new NotFoundHttpException('Не найден бренд');
        }

        $searchModel = new BrandItemSearch([
            'id_brand' => $brand->id
        ]);
        $dataProvider = $searchModel->search(\Yii::$app->request->get());

        return $this->render('items', [
            'brand' => $brand,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionCatalog($id)
    {
        if (!$brand = Brand::findOne(['id' => $id])) {
            throw new NotFoundHttpException('Не найден бренд');
        }

        $searchModel = new CatalogSearch([
            'id_brand' => $brand->id
        ]);
        $dataProvider = $searchModel->search(\Yii::$app->request->get());

        return $this->render('catalog', [
            'brand' => $brand,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionProducts($id)
    {
        if (!$catalog = Catalog::findOne(['id' => $id])) {
            throw new NotFoundHttpException('Не найден каталог');
        }

        $searchModel = new CatalogProductSearch([
            'id_catalog' => $catalog->id
        ]);
        $dataProvider = $searchModel->search(\Yii::$app->request->get());

        return $this->render('products', [
            'catalog' => $catalog,
            'brand' => $catalog->brand,
            'dataProvider' => $dataProvider,
        ]);
    }
}

modules/admin/views/brand/_form.php
<?php

use app\modules\admin\models\forms\BrandForm;
use app\modules\admin\widgets\WisywygWidget;
use yii\helpers\Html;
use app\modules\admin\widgets\Form;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model BrandForm */
?>

<div>

    <?php $form = Form::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'name')->textInput() ?>
    <?= $form->field($model, 'description')->textarea() ?>
    <?= $form->imageField($model, 'image')->fileInput() ?>
    <?= $form->imageField($model, 'logo')->fileInput() ?>
    <?= $form->imageField($model, 'page_image')->fileInput() ?>
    <?= $form->field($model, 'content')->widget(WisywygWidget::class, ['options' => ['rows' => 20]])?>
    <?= $form->field($model, 'is_published')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Отмена',  Url::to(['brand/index']), ['class' => 'btn btn-default']) ?>
    </div>

    <?php Form::end(); ?>

</div>

modules/admin/views/brand/advantages.php
<?php

use app\models\db\Brand;
use app\modules\admin\grid\AdminGridView;
use app\modules\admin\grid\StatusColumn;
use app\modules\admin\widgets\Actions;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $brand Brand */

$this->title = $brand->name . '. Преимущества';
$this->params['breadcrumbs'][] = ['label' => 'Бренды', 'url' => Url::to(['brand/index'])];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-body">
        <?= Actions::widget(['controller' => 'brand-advantage', 'item' => $brand, 'buttons' => ['create']]);?>
        <table class="table table-bordered table-hover">
            <?=AdminGridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    [
                        'attribute' => 'text',
                        'format' => 'raw',
                        'options' => ['width' => '80%'],
                    ],
                    [
                        'class' => StatusColumn::class
                    ],
                    [
                        'label' => 'Действия',
                        'format' => 'raw',
                        'contentOptions' => [
                            'nowrap' => 'nowrap'
                        ],
                        'value' => function($item) {
                            return Actions::widget([
                                'controller' => 'brand-advantage',
                                'item' => $item,
                                'buttons' => ['edit', 'delete']
                            ]);
                        }
                    ],
                ]
            ]);
            ?>
        </table>
    </div>
</div>

modules/admin/views/brand/catalog.php
<?php

use app\models\db\Brand;
use app\models\db\Catalog;
use app\modules\admin\grid\AdminGridView;
use app\modules\admin\grid\StatusColumn;
use app\modules\admin\widgets\Actions;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $brand Brand */

$this->title = 'Каталог ' . $brand->name;
$this->params['breadcrumbs'][] = ['label' => 'Бренды', 'url' => Url::to(['brand/index'])];
$this->params['breadcrumbs'][] = $brand->name;
?>
<div class="box">
    <div class="box-body">
        <?= Actions::widget(['controller' => 'catalog', 'item' => $brand, 'buttons' => ['create']]);?>
        <table class="table table-bordered table-hover">
            <?=AdminGridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    [
                        'attribute' => 'img_ext',
                        'format' => 'raw',
                        'options' => ['width' => '10%'],
                        'value' => function(Catalog $model) {
                            $img = $model->getImage('610x400');
                            if (!empty($img)) {
                                return Html::img($img, ['width' => 100]);
                            } else {
                                return '';
                            }
                        }
                    ],
                    [
                        'attribute' => 'name',
                        'format' => 'raw',
                        'options' => ['width' => '80%'],
                        'value' => function(Catalog $model) {
                            $link = Html::a('Продукты', Url::to(['brand/products', 'id' => $model->id]));
                            return "<b>{$model->name}</b><br>[{$link}]";
                        }
                    ],
                    [
                        'class' => StatusColumn::class
                    ],
                    [
                        'label' => 'Действия',
                        'format' => 'raw',
                        'contentOptions' => [
                            'nowrap' => 'nowrap'
                        ],
                        'value' => function($item) {
                            return Actions::widget([
                                'controller' => 'catalog',
                                'item' => $item,
                                'buttons' => ['edit', 'delete']
                            ]);
                        }
                    ],
                ]
            ]);
            ?>
        </table>
    </div>
</div>

modules/admin/views/brand/create.php
<?php

use app\modules\admin\models\forms\BrandForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model BrandForm */

$this->title = 'Добавление бренда';
$this->params['breadcrumbs'][] = ['label' => 'Бренды', 'url' => Url::to(['brand/index'])];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-body">
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>
    </div>
</div>

modules/admin/views/brand/edit.php
<?php

use app\modules\admin\models\forms\BrandForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model BrandForm */

$this->title = 'Редактирование бренда ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Бренды', 'url' => Url::to(['brand/index'])];
$this->params['breadcrumbs'][] = 'Редактировать';
?>
<div class="box">
    <div class="box-body">
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>
    </div>
</div>

modules/admin/views/brand/index.php
<?php

use app\models\db\Brand;
use app\modules\admin\grid\AdminGridView;
use app\modules\admin\grid\StatusColumn;
use app\modules\admin\widgets\Actions;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Бренды';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-body">
        <?= Actions::widget(['controller' => 'brand', 'buttons' => ['create']]);?>
        <table class="table table-bordered table-hover">
            <?=AdminGridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    [
                        'attribute' => 'img_ext',
                        'format' => 'raw',
                        'options' => ['width' => '10%'],
                        'value' => function(Brand $model) {
                            $img = $model->getImage('610x400');
                            if (!empty($img)) {
                                return Html::img($img, ['width' => 100]);
                            } else {
                                return '';
                            }
                        }
                    ],
                    [
                        'attribute' => 'name',
                        'options' => ['width' => '80%'],
                        'format' => 'raw',
                        'value' => function(Brand $model) {
                            $catalogLink = Html::a('Каталог', Url::to(['brand/catalog', 'id' => $model->id]));
                            $advantagesLink = Html::a('Преимущества', Url::to(['brand/advantages', 'id' => $model->id]));
                            $itemsLink = Html::a('Особенности', Url::to(['brand/items', 'id' => $model->id]));
                            $videoLink = Html::a('Видео', Url::to(['brand/video', 'id' => $model->id]));
                            $qouteLink = Html::a('Цитата', Url::to(['brand/quote', 'id' => $model->id]));
                            return "<b>{$model->name}</b><br>
                                [{$catalogLink}]<br>
                                [{$advantagesLink}]<br>
                                [{$itemsLink}]<br>
                                [{$videoLink}]<br>
                                [{$qouteLink}]
                            ";
                        }
                    ],
                    [
                        'class' => StatusColumn::class
                    ],
                    [
                        'label' => 'Действия',
                        'format' => 'raw',
                        'contentOptions' => [
                            'nowrap' => 'nowrap'
                        ],
                        'value' => function($item) {
                            return Actions::widget([
                                'controller' => 'brand',
                                'item' => $item,
                                'buttons' => ['edit', 'delete']
                            ]);
                        }
                    ],
                ]
            ]);
            ?>
        </table>
    </div>
</div>

modules/admin/views/brand/items.php
<?php

use app\models\db\Brand;
use app\models\db\BrandItem;
use app\modules\admin\grid\AdminGridView;
use app\modules\admin\grid\StatusColumn;
use app\modules\admin\widgets\Actions;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $brand Brand */

$this->title = $brand->name . '. Особенности';
$this->params['breadcrumbs'][] = ['label' => 'Бренды', 'url' => Url::to(['brand/index'])];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-body">
        <?= Actions::widget(['controller' => 'brand-item', 'item' => $brand, 'buttons' => ['create']]);?>
        <table class="table table-bordered table-hover">
            <?=AdminGridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    [
                        'attribute' => 'img_ext',
                        'format' => 'raw',
                        'options' => ['width' => '10%'],
                        'value' => function(BrandItem $model) {
                            $img = $model->getImage('100x100');
                            if (!empty($img)) {
                                return Html::img($img, ['width' => 100]);
                            } else {
                                return '';
                            }
                        }
                    ],
                    [
                        'attribute' => 'name',
                        'format' => 'raw',
                        'options' => ['width' => '10%'],
                    ],
                    [
                        'attribute' => 'text',
                        'format' => 'raw',
                        'options' => ['width' => '60%'],
                    ],
                    [
                        'class' => StatusColumn::class
                    ],
                    [
                        'label' => 'Действия',
                        'format' => 'raw',
                        'contentOptions' => [
                            'nowrap' => 'nowrap'
                        ],
                        'value' => function($item) {
                            return Actions::widget([
                                'controller' => 'brand-item',
                                'item' => $item,
                                'buttons' => ['edit', 'delete']
                            ]);
                        }
                    ],
                ]
            ]);
            ?>
        </table>
    </div>
</div>

modules/admin/views/brand/products.php
<?php

use app\models\db\Brand;
use app\models\db\Catalog;
use app\models\db\CatalogProduct;
use app\modules\admin\grid\AdminGridView;
use app\modules\admin\widgets\Actions;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $brand Brand */
/* @var $catalog Catalog */

$this->title = $brand->name . '. ' . $catalog->name;
$this->params['breadcrumbs'][] = ['label' => 'Бренды', 'url' => Url::to(['brand/index'])];
$this->params['breadcrumbs'][] = ['label' => $brand->name, 'url' => Url::to(['brand/catalog', 'id' => $brand->id])];
$this->params['breadcrumbs'][] = $catalog->name;
?>
<div class="box">
    <div class="box-body">
        <?= Actions::widget(['controller' => 'catalog-product', 'item' => $catalog, 'buttons' => ['create']]);?>
        <table class="table table-bordered table-hover">
            <?=AdminGridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    [
                        'attribute' => 'img_ext',
                        'format' => 'raw',
                        'options' => ['width' => '10%'],
                        'value' => function(CatalogProduct $model) {
                            $img = $model->getImage('290x290');
                            if (!empty($img)) {
                                return Html::img($img, ['width' => 100]);
                            } else {
                                return '';
                            }
                        }
                    ],
                    [
                        'attribute' => 'name',
                        'format' => 'raw',
                        'options' => ['width' => '80%'],
                    ],
                    [
                        'attribute' => 'is_published',
                        'format' => 'raw',
                        'options' => ['width' => '5%'],
                        'label' => 'Статус',
                        'value' => function(CatalogProduct $model){
                            return Html::tag('i', '&nbsp', [
                                'class' => 'fa fa-fw fa-lightbulb-o',
                                'style' => 'font-size: 2rem;color: ' . ($model->is_published ? 'green' : 'red')
                            ]);
                        }
                    ],
                    [
                        'label' => 'Действия',
                        'format' => 'raw',
                        'contentOptions' => [
                            'nowrap' => 'nowrap'
                        ],
                        'value' => function($item) {
                            return Actions::widget([
                                'controller' => 'catalog-product',
                                'item' => $item,
                                'buttons' => ['edit', 'delete']
                            ]);
                        }
                    ],
                ]
            ]);
            ?>
        </table>
    </div>
</div>

modules/admin/views/brand/quote.php
<?php

use app\models\db\Brand;
use app\models\db\BrandQuote;
use app\modules\admin\grid\AdminGridView;
use app\modules\admin\grid\StatusColumn;
use app\modules\admin\widgets\Actions;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $brand Brand */

$this->title = $brand->name . '. Цитата';
$this->params['breadcrumbs'][] = ['label' => 'Бренды', 'url' => Url::to(['brand/index'])];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-body">
        <?php if(!BrandQuote::find()->count()) { ?>
            <?= Actions::widget(['controller' => 'brand-quote', 'item' => $brand, 'buttons' => ['create']]);?>
        <?php }?>
        <table class="table table-bordered table-hover">
            <?=AdminGridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    [
                        'attribute' => 'img_ext',
                        'format' => 'raw',
                        'options' => ['width' => '10%'],
                        'value' => function(BrandQuote $model) {
                            $img = $model->getImage('1872x450');
                            if (!empty($img)) {
                                return Html::img($img, ['width' => 100]);
                            } else {
                                return '';
                            }
                        }
                    ],
                    [
                        'attribute' => 'text',
                        'format' => 'raw',
                    ],
                    [
                        'class' => StatusColumn::class
                    ],
                    [
                        'label' => 'Действия',
                        'format' => 'raw',
                        'contentOptions' => [
                            'nowrap' => 'nowrap'
                        ],
                        'value' => function($item) {
                            return Actions::widget([
                                'controller' => 'brand-quote',
                                'item' => $item,
                                'buttons' => ['edit', 'delete']
                            ]);
                        }
                    ],
                ]
            ]);
            ?>
        </table>
    </div>
</div>

modules/admin/views/brand/video.php
<?php

use app\models\db\Brand;
use app\models\db\BrandVideo;
use app\modules\admin\grid\AdminGridView;
use app\modules\admin\grid\StatusColumn;
use app\modules\admin\widgets\Actions;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $brand Brand */

$this->title = $brand->name . '. Видео';
$this->params['breadcrumbs'][] = ['label' => 'Бренды', 'url' => Url::to(['brand/index'])];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-body">
        <?= Actions::widget(['controller' => 'brand-video', 'item' => $brand, 'buttons' => ['create']]);?>
        <table class="table table-bordered table-hover">
            <?=AdminGridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    [
                        'attribute' => 'name',
                        'format' => 'raw',
                        'options' => ['width' => '80%'],
                        'value' => function(BrandVideo $model){
                            $videoLink = Html::a('Посмотреть видео', $model->getUrl(), ['target' => '_blank']);
                            return "<b>{$model->name}</b><br>{$videoLink}";
                        }
                    ],
                    [
                        'class' => StatusColumn::class
                    ],
                    [
                        'label' => 'Действия',
                        'format' => 'raw',
                        'contentOptions' => [
                            'nowrap' => 'nowrap'
                        ],
                        'value' => function($item) {
                            return Actions::widget([
                                'controller' => 'brand-video',
                                'item' => $item,
                                'buttons' => ['edit', 'delete']
                            ]);
                        }
                    ],
                ]
            ]);
            ?>
        </table>
    </div>
</div>