modules/admin/controllers/AdminController.php
<?php

namespace app\modules\admin\controllers;

use app\modules\admin\AdminModule;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use app\modules\admin\models\LoginForm;

class AdminController extends Controller
{
    /** @var AdminModule */
    public $module;

    /** @var string  */
    public $layout = 'main';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
                'user' => $this->module->admin
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * @return string
     */
    public function actionError()
    {
        $exception = Yii::$app->errorHandler->exception;
        return $this->render('error', [
            'name' => 'Ошибка',
            'message' => $exception->getMessage()
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        $user = $this->module->admin;
        if (!$user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->renderPartial('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        $this->module->admin->logout();

        return $this->goHome();
    }

    /**
     * @param null $defaultUrl
     * @return \yii\console\Response|Response
     */
    public function goBack($defaultUrl = null)
    {
        return Yii::$app->getResponse()->redirect($this->module->admin->getReturnUrl($defaultUrl));
    }
}

modules/admin/controllers/CarMapController.php
<?php

namespace app\modules\admin\controllers;

use app\models\db\CarMap;
use app\models\db\CarModel;
use app\modules\admin\models\forms\CarMapForm;
use app\modules\admin\models\search\BaseSearch;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;

class CarMapController extends AdminBaseController
{
    public $searchModel = BaseSearch::class;
    public $formModel = CarMapForm::class;
    public $objectClass = CarMap::class;

    /**
     * @param $id
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionCreate($id)
    {
        if (!$carModel = CarModel::findOne(['id' => $id])) {
            throw new NotFoundHttpException('Не найдена модель автомобиля');
        }

        $model = new CarMapForm([
            'objectClass' => $this->objectClass,
            'id_model' => $carModel->id
        ]);
        $request = \Yii::$app->request;

        if ($request->isPost && $model->load($request->post()) && $model->create()) {
            \Yii::$app->session->setFlash('success', 'Запись успешно создана');
            return $this->redirect(Url::to(['maps/files', 'id' => $carModel->id]));
        } else {
            if ($request->isPost) {
                \Yii::$app->session->setFlash('error', 'Ошибка при создани записи');
            }

            return $this->render('create', [
                'model' => $model,
                'brand' => $carModel->brand,
                'carModel' => $carModel
            ]);
        }
    }

    /**
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionEdit()
    {
        /** @var CarMap $item */
        $item = $this->getRequestedObject(\Yii::$app->request->get('id'));

        $model = new CarMapForm(['id_model' => $item->id_model]);
        $model->import($item);
        $request = \Yii::$app->request;

        if ($request->isPost && $model->load($request->post()) && $model->edit($item)) {
            \Yii::$app->session->setFlash('success', 'Изменения сохранены');
            return $this->redirect(Url::to(['maps/files', 'id' => $item->id_model]));
        } else {
            if ($request->isPost) {
                \Yii::$app->session->setFlash('error', 'Ошибка при редактировании записи');
            }

            return $this->render('edit', [
                'model' => $model,
                'carModel' => $item->model,
                'brand' => $item->model->brand
            ]);
        }
    }

    /**
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     * @throws \Throwable
     */
    public function actionDelete()
    {
        /** @var CarMap $item */
        $item = $this->getRequestedObject(\Yii::$app->request->get('id'));

        try {
            $item->delete();
            \Yii::$app->session->setFlash('success', 'Запись удалена');
            return $this->redirect(Url::to(['maps/files', 'id' => $item->id_model]));
        } catch (\Exception $e) {
            \Yii::$app->session->setFlash('error', 'Ошибка при удалении записи');
            return $this->redirect(Url::to(['maps/files', 'id' => $item->id_model]));
        }
    }
}

modules/admin/controllers/MapsController.php
<?php

namespace app\modules\admin\controllers;

use app\models\db\CarBrand;
use app\models\db\CarModel;
use app\modules\admin\models\search\BaseSearch;
use app\modules\admin\models\search\CarMapSearch;
use app\modules\admin\models\search\CarModelSearch;
use yii\web\NotFoundHttpException;

class MapsController extends AdminBaseController
{
    public $searchModel = BaseSearch::class;
    public $objectClass = CarBrand::class;

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     * @throws \yii\base\InvalidConfigException
     */
    public function actionModels($id)
    {
        if (!$brand = CarBrand::findOne(['id' => $id])) {
            throw new NotFoundHttpException('Не найдена марка автомобиля');
        }

        $searchModel = new CarModelSearch([
            'id_brand' => $brand->id
        ]);
        $dataProvider = $searchModel->search(\Yii::$app->request->get());

        return $this->render('models', [
            'brand' => $brand,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionFiles($id)
    {
        if (!$model = CarModel::findOne(['id' => $id])) {
            throw new NotFoundHttpException('Не найдена модель автомобиля');
        }

        $searchModel = new CarMapSearch([
            'id_model' => $model->id
        ]);
        $dataProvider = $searchModel->search(\Yii::$app->request->get());

        return $this->render('files', [
            'brand' => $model->brand,
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }
}

modules/admin/views/car-map/_form.php
<?php

use app\models\db\CarModel;
use app\modules\admin\models\forms\CarModelForm;
use yii\helpers\Html;
use yii\helpers\Url;
use app\modules\admin\widgets\Form;

/* @var $this yii\web\View */
/* @var $model CarModelForm */
/* @var $carModel CarModel */

?>

<div>

    <?php $form = Form::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'name')->textInput() ?>
    <?= $form->fileField($model, 'file')->fileInput() ?>
    <?= $form->field($model, 'is_published')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Отмена',  Url::to(['maps/files', 'id' => $carModel->id]), ['class' => 'btn btn-default']) ?>
    </div>

    <?php Form::end(); ?>

</div>

modules/admin/views/car-map/create.php
<?php

use app\models\db\CarBrand;
use app\models\db\CarModel;
use app\modules\admin\models\forms\CarModelForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model CarModelForm */
/* @var $brand CarBrand */
/* @var $carModel CarModel */

$this->title = 'Добавление файла';
$this->params['breadcrumbs'][] = ['label' => 'Тех. карты', 'url' => Url::to(['maps/index'])];
$this->params['breadcrumbs'][] = ['label' => $brand->name, 'url' => Url::to(['maps/models', 'id' => $brand->id])];
$this->params['breadcrumbs'][] = ['label' => $carModel->name, 'url' => Url::to(['maps/files', 'id' => $carModel->id])];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-body">
        <?= $this->render('_form', [
            'model' => $model,
            'carModel' => $carModel
        ]) ?>
    </div>
</div>

modules/admin/views/car-map/edit.php
<?php

use app\models\db\CarBrand;
use app\models\db\CarModel;
use app\modules\admin\models\forms\CarModelForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model CarModelForm */
/* @var $brand CarBrand */
/* @var $carModel CarModel */

$this->title = 'Редактирование файла ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Тех. карты', 'url' => Url::to(['maps/index'])];
$this->params['breadcrumbs'][] = ['label' => $brand->name, 'url' => Url::to(['maps/models', 'id' => $brand->id])];
$this->params['breadcrumbs'][] = ['label' => $carModel->name, 'url' => Url::to(['maps/files', 'id' => $carModel->id])];
$this->params['breadcrumbs'][] = $model->name;
?>
<div class="box">
    <div class="box-body">
        <?= $this->render('_form', [
            'model' => $model,
            'carModel' => $carModel
        ]) ?>
    </div>
</div>