modules/admin/controllers/UsersController.php
<?php

namespace app\modules\admin\controllers;

use app\modules\admin\controllers\traits\CreateTrait;
use app\modules\admin\controllers\traits\DeleteTrait;
use app\modules\admin\controllers\traits\UpdateTrait;
use app\modules\admin\models\AdminUser;
use app\modules\admin\models\forms\UsersForm;
use app\modules\admin\models\search\UsersSearch;

class UsersController extends AdminBaseController
{
    public $searchModel = UsersSearch::class;
    public $formModel = UsersForm::class;
    public $objectClass = AdminUser::class;

    use CreateTrait, DeleteTrait, UpdateTrait;

    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new $this->searchModel();
        $dataProvider = $searchModel->search(\Yii::$app->request->get());
        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }
}

modules/admin/views/users/create.php
<?php

use yii\helpers\Url;

/** @var \yii\web\View $this */

$this->title = 'Добавление пользователя';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => Url::to(['users/index'])];
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="box">
    <div class="box-body">
        <?=$this->render('form', ['model' => $model]) ?>
    </div>
</div>

modules/admin/views/users/edit.php
<?php

use app\modules\admin\models\forms\UsersForm;
use yii\helpers\Url;

/** @var \yii\web\View $this */
/** @var $model UsersForm */

$this->title = 'Редактирование пользователя ' . $model->login;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => Url::to(['users/index'])];
$this->params['breadcrumbs'][] = $model->login;

?>

<div class="box">
    <div class="box-body">
        <?=$this->render('form', ['model' => $model]) ?>
    </div>
</div>

modules/admin/views/users/form.php
<?php

use yii\helpers\Html;
use app\modules\admin\widgets\Form;
use yii\helpers\Url;

?>

<div class="user-form">
    <?php $form = Form::begin(); ?>
    <?= $form->field($model, 'login')->textInput() ?>
    <?= $form->field($model, 'password')->passwordInput() ?>
    <?= $form->field($model, 'passwordRepeat')->passwordInput() ?>

    <div class="form-group">
        <?= Html::submitButton( 'Сохранить',  ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Отмена',  Url::to(['users/index']), ['class' => 'btn btn-default']) ?>
    </div>
    <?php Form::end(); ?>
</div>

modules/admin/views/users/index.php
<?php

use app\modules\admin\grid\AdminGridView;
use app\modules\admin\widgets\Actions;

/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Админ. пользователи';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box">
    <div class="box-body">
        <?= Actions::widget(['controller' => 'users', 'buttons' => ['create']]);?>
        <table class="table table-bordered table-hover">
            <?= AdminGridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    'id',
                    [
                        'label' => 'Логин',
                        'attribute' => 'login',
                        'options' => ['width' => '70%']

                    ],
                    [
                        'label' => 'Время последнего входа',
                        'attribute' => 'last_login',
                        'value' => 'last_login',
                    ],
                    [
                        'label' => 'Действия',
                        'format' => 'raw',
                        'value' => function($item) {
                            return Actions::widget([
                                'controller' => 'users',
                                'item' => $item,
                                'buttons' => ['edit', 'delete']
                            ]);
                        }
                    ],
                ]
            ]);
            ?>
        </table>
    </div>
</div>